repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: detect-private-key

  # - repo: local
  #   hooks:
  #     - id: standardrb
  #       name: check Ruby style with StandardRB
  #       description: Check Ruby style with StandardRB
  #       entry: .bin/standardrb.sh
  #       language: script
  #       types: ["ruby"]
  #       stages: [pre-commit]
  #       verbose: true
